### ISSUE TITLE
pip install python-geohash

### ISSUE THREAD

**Issue by jgruber96** [FortDigital/covid-19#7]
after doing pip install python-geohash, and running the .py script, I get an error on line 8 of the .py script

`user@covid:~$ python3 /home/user/covid/covid19_NewDataset.py
Traceback (most recent call last):
  File "/home/user/covid/covid19_NewDataset.py", line 8, in <module>
    import geohash
ModuleNotFoundError: No module named 'geohash'`

**Comment by GattoJohnny** [comment]
Hello, @jgruber96 , I got the same message. How did you eliminate the problem?

**Comment by jgruber96** [comment]
> Hello, I got the same message. How did you eliminate the problem?

Try doing pip3 install geohash

**Comment by GattoJohnny** [comment]
Thanks for your kind assistance.
