### ISSUE TITLE
No data from April

### ISSUE THREAD

**Issue by zerocrashhh** [FortDigital/covid-19#8]
Hi, graphs are stuck in March, no data from April.
Thx for the great Dashboard btw.
Cheers

**Comment by FortDigital** [comment]
Hi zerocrashhh,

Thanks for the feedback and for bringing this to our attention.It looks like JHU updated their data a little later than usual so the scheduled run missed the changes.

Ive just rerun the Collection script so it should now be up to date, ive also set the scheduled task to run a little later just to allow a bit more time.

Regards
Jamie
